variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"

stages:
  - deploy

deploy:
  stage: deploy
  image: nohitme/hugo-firebase
  script:
    # build site
    - cd ${CI_PROJECT_DIR}
    - hugo
    # upload
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --token ${FIREBASE_TOKEN} --only hosting
  only:
    - master
